### ISSUE TITLE
Creating an index.html + Github Pages Hosting

### ISSUE THREAD

**Issue by zesoft23** [UniCourt/cic-code-ga#3]
This is a bit hard to access right now since you have to navigate to a particular title first. Have y'all thought about:

1. Creating an index.html to make this more accessible and more "hostable"
2. Creating a [Github Pages](https://pages.github.com/) for this site along with that index.html I love that y'all are hosting on the internet archive though!

Cheers and appreciate y'all's effort.

**Comment by pshenoy-uc** [comment]
@zesoft23 This is already in the pipeline. We will be adding an index and making this more navigable.

**Comment by glen-uc** [comment]
@zesoft23 Thanks for your inputs, we have added a index.html containing links to all the releases in the v1.1-dev branch 

The changes should reflect in the GitHub pages next release

**Comment by pshenoy-uc** [comment]
Fixed in Release v1.1
